services:
  postgres-db:
    container_name: userManagement
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: management
      POSTGRES_DB: userManagement
    ports:
      - "5432:5432"