CREATE TABLE user_cards
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    address  VARCHAR(255),
    city     VARCHAR(255),
    state    VARCHAR(255),
    email    VARCHAR(255),
    phone    VARCHAR(255),
    img_link VARCHAR(255),
    CONSTRAINT pk_usercards PRIMARY KEY (id)
);